rootProject.name = 'HexPlugins'

include 'plugins:HexCore'
include 'plugins:UiExample'
include 'plugins:DbExample'
include 'plugins:HexVelocityFallback'
include 'plugins:Minigames'
include 'plugins:HexPortals'
include 'plugins:WaterLevelFlood'
include 'plugins:WaterDrawn'
include 'plugins:IcebergEvent'
include 'plugins:AreaEffects'
include 'plugins:HexElimination'
include 'plugins:HexCustomMobs'
include 'plugins:HexNPC'
include 'plugins:HexSequence'
include 'plugins:HexTowns'
include 'plugins:HexMinions'
include 'plugins:HexSkills'
include 'plugins:HexQuests'
include 'plugins:HexCollections'
include 'plugins:HexEconomy'
include 'plugins:HexAuctionBazaar'
include 'plugins:HexRankExpiry'
include 'plugins:VishopBroadcast'
include 'statsapi'

// Physical folder is 'Plugins/...' (capital P), keep logical Gradle path consistent.
project(':plugins:HexCore').projectDir = file('Plugins/HexCore')
project(':plugins:UiExample').projectDir = file('Plugins/UiExample')
project(':plugins:DbExample').projectDir = file('Plugins/DbExample')
project(':plugins:HexVelocityFallback').projectDir = file('Plugins/HexVelocityFallback')
project(':plugins:Minigames').projectDir = file('Plugins/Minigames')
project(':plugins:HexPortals').projectDir = file('Plugins/HexPortals')
project(':plugins:WaterLevelFlood').projectDir = file('Plugins/WaterLevelFlood')
project(':plugins:WaterDrawn').projectDir = file('Plugins/WaterDrawn')
project(':plugins:IcebergEvent').projectDir = file('Plugins/IcebergEvent')
project(':plugins:AreaEffects').projectDir = file('Plugins/AreaEffects')
project(':plugins:HexElimination').projectDir = file('Plugins/HexElimination')
project(':plugins:HexCustomMobs').projectDir = file('Plugins/HexCustomMobs')
project(':plugins:HexNPC').projectDir = file('Plugins/HexNPC')
project(':plugins:HexSequence').projectDir = file('Plugins/HexSequence')
project(':plugins:HexTowns').projectDir = file('Plugins/HexTowns')
project(':plugins:HexMinions').projectDir = file('Plugins/HexMinions')
project(':plugins:HexSkills').projectDir = file('Plugins/HexSkills')
project(':plugins:HexQuests').projectDir = file('Plugins/HexQuests')
project(':plugins:HexCollections').projectDir = file('Plugins/HexCollections')
project(':plugins:HexEconomy').projectDir = file('Plugins/HexEconomy')
project(':plugins:HexAuctionBazaar').projectDir = file('Plugins/HexAuctionBazaar')
project(':plugins:HexRankExpiry').projectDir = file('Plugins/HexRankExpiry')
project(':plugins:VishopBroadcast').projectDir = file('Plugins/VishopBroadcast')
project(':statsapi').projectDir = file('StatsApi')
