rootProject.name = 'HexPlugins'

include 'plugins:HexCore'
include 'plugins:UiExample'
include 'plugins:DbExample'
include 'plugins:HexVelocityFallback'
include 'plugins:Minigames'
include 'plugins:HexPortals'
include 'plugins:HexDailyRewards'
include 'plugins:HexAfkZone'
include 'plugins:HexChests'
include 'plugins:HexCasino'
