rootProject.name = 'HexPlugins'

include ':plugins'
project(':plugins').projectDir = file('gradle/plugins')

def pluginProjects = [
    'AreaEffects',
    'DbExample',
    'HexCasino',
    'HexCollections',
    'HexCore',
    'HexCustomItems',
    'HexEconomy',
    'HexElimination',
    'HexEndEvent',
    'HexEventBossFight',
    'HexEvents',
    'HexGUI',
    'HexMinions',
    'HexNameTags',
    'HexNPC',
    'HexPortals',
    'HexQuests',
    'HexRankExpiry',
    'HexRestrictions',
    'HexSequence',
    'HexSkills',
    'HexTowns',
    'HexVelocityFallback',
    'IcebergEvent',
    'Minigames',
    'StatsApi',
    'UiExample',
    'VishopBroadcast',
    'VishopBroadcastProxy',
    'WaterDrawn',
    'WaterLevelFlood',
    'hexdisplayabovename'
]

pluginProjects.each { pluginName ->
    include ":plugins:${pluginName}"
    project(":plugins:${pluginName}").projectDir = file(pluginName)
}

include ':plugins:HexEvents:hexevents-api'
project(':plugins:HexEvents:hexevents-api').projectDir = file('HexEvents/hexevents-api')
include ':plugins:HexEvents:hexevents-plugin'
project(':plugins:HexEvents:hexevents-plugin').projectDir = file('HexEvents/hexevents-plugin')

