plugins {
    id 'java'
}

group = 'hex'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly project(':plugins:HexEvents:hexevents-api')
    compileOnly project(':plugins:HexCore')
    testImplementation 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    testImplementation project(':plugins:HexEvents:hexevents-api')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

jar {
    archiveFileName = "HexMinigames-${version}.jar"
}
